---
# no_log: true
# - hosts: servers
#   gather_facts: True
#   become: yes
#   become_method: sudo
#   tags:
#     - bootstrap
#   roles:
#     - role: boss-ansible-role-bootstrap
#     - role: boss-ansible-role-core
#     - role: boss-ansible-role-fact
#     - role: boss-ansible-role-environment
#     - role: boss-ansible-role-etckeeper

- hosts: servers
  gather_facts: True
  become: yes
  become_method: sudo
  tags:
    - update_hosts
  roles:
    - role: ../
