# https://gist.github.com/gnarf/b103e77f37236ca72d8e
:vms:
  hosts-test-01:
    :hostname: "hosts-test-01"
    :ip: "192.168.13.100"
    :ram: 1024
    :cpu: 2
    :box: "ubuntu/xenial64"

  hosts-test-02:
    :hostname: "hosts-test-02"
    :ip: "192.168.13.101"
    :ram: 1024
    :cpu: 2
    :box: "ubuntu/xenial64"

:groups:
  hosts-test-01:
    - hosts-test-01
  hosts-test-02:
    - hosts-test-02
  host-stest-0_servers:
    - hosts-test-01
    - hosts-test-02
  servers:
    - hosts-test-01
    - hosts-test-02
  dns_servers:
    - hosts-test-01
    - hosts-test-02
