---
# tasks file for boss-ansible-role-update-hosts

- name: debug groups
  debug: msg='{{groups}}'

- name: debug hostvars
  debug: msg='{{hostvars}}'

# ORIG
# # SOURCE: https://github.com/idegard/ansible-simple-swarm/blob/8272763a350d88b64380160af2512f8d271055c1/basic.yml
# - name: Ensure IP address of all hosts to all hosts
#   lineinfile:
#     dest: "{{boss__update__hosts__hosts_file}}"
#     line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ hostvars[item].inventory_hostname }} {{ hostvars[item].inventory_hostname_short }}"
#     state: present
#   with_items: "{{ groups[boss__update__hosts__ansible_group] }}"

# FIXME: replace with this!
#  command: "kubeadm init --apiserver-advertise-address={{ hostvars[groups['kubernetes-master'][0]]['ansible_' + kubernetes_interface].ipv4.address }} --token {{ kubeadm_clusterToken }}"

# SOURCE: https://github.com/idegard/ansible-simple-swarm/blob/8272763a350d88b64380160af2512f8d271055c1/basic.yml
- name: debug dump groups.servers
  debug:
    msg: "{{ hostvars[item]['ansible_' + boss__update__hosts__ansible_group ].ipv4.address }}"
  with_items: "{{ groups[boss__update__hosts__ansible_group] }}"

# SOURCE: https://github.com/idegard/ansible-simple-swarm/blob/8272763a350d88b64380160af2512f8d271055c1/basic.yml
- name: Ensure IP address of all hosts to all hosts
  lineinfile:
    dest: "{{boss__update__hosts__hosts_file}}"
    line: "{{ hostvars[item]['ansible_' + boss__update__hosts__ansible_group ].ipv4.address }} {{ hostvars[item].inventory_hostname }} {{ hostvars[item].inventory_hostname_short }}"
    state: present
  with_items: "{{ groups[boss__update__hosts__ansible_group] }}"
