---
- name: Converge
  hosts: all
  gather_facts: True

  vars:
    boss__update__hosts__hosts_file: /etc/hosts.molecule

  roles:
    - role: boss-ansible-role-update-hosts
      bossjones__user: vagrant
      bossjones__group: vagrant
      boss__update__hosts__hosts_file: /etc/hosts.molecule
      boss__update__hosts__ansible_group: "servers"
      boss__update__hosts__networking_interface: "lo0"

